;; Generated by genconfig.  DO NOT EDIT
(define-module gauche.config
  (export gauche-config))
(select-module gauche.config)

(define (gauche-config param)
  (cond [(assoc param *configurations*) => (^p (replace-install-dir (cadr p)))]
        [else (error "unknown configuration parameter name" param)]))

(define (replace-install-dir str)
  (let1 ss (string-split str #\@)
    (if (length<=? ss 1)
      str
      (if-let1 d ((with-module gauche.internal %gauche-runtime-directory))
        (string-join ss d)
        (error "Couldn't obtain installation directory.")))))

(define *configurations*
  (quote
   (("-V"  "0.9.13_pre2")
    ("-I"  "-I/opt/yunibase/current/gauche/lib/gauche-0.98/0.9.13_pre2/include")
    ("-L"  "-L/opt/yunibase/current/gauche/lib/gauche-0.98/0.9.13_pre2/x86_64-pc-linux-gnu ")
    ("--ac"  "/opt/yunibase/current/gauche/share/gauche-0.98/0.9.13_pre2/")
    ("-l"  "-lgauche-0.98 -lcrypt -lrt -lm  -lpthread")
    ("--cc"  "gcc")
    ("--reconfigure"  "./configure  '--prefix=/opt/yunibase/current/gauche' '--without-iconv' '--enable-multibyte=utf-8'")

    ("--prefix"       "/opt/yunibase/current/gauche")
    ("--sysincdir"    "/opt/yunibase/current/gauche/lib/gauche-0.98/0.9.13_pre2/include")
    ("--siteincdir"   "/opt/yunibase/current/gauche/lib/gauche-0.98/site/include")
    ("--pkgincdir"    "${libdir}/gauche-0.98/site/include")
    ("--syslibdir"    "/opt/yunibase/current/gauche/share/gauche-0.98/0.9.13_pre2/lib")
    ("--sitelibdir"   "/opt/yunibase/current/gauche/share/gauche-0.98/site/lib")
    ("--pkglibdir"    "${datadir}/gauche-0.98/site/lib")
    ("--sysarchdir"   "/opt/yunibase/current/gauche/lib/gauche-0.98/0.9.13_pre2/x86_64-pc-linux-gnu")
    ("--sitearchdir"  "/opt/yunibase/current/gauche/lib/gauche-0.98/site/x86_64-pc-linux-gnu")
    ("--pkgarchdir"   "${libdir}/gauche-0.98/site/x86_64-pc-linux-gnu")
    ("--mandir"       "/opt/yunibase/current/gauche/share/man")
    ("--infodir"      "/opt/yunibase/current/gauche/share/info")
    ("--arch"         "x86_64-pc-linux-gnu")

    ("--incdirs"      "/opt/yunibase/current/gauche/lib/gauche-0.98/0.9.13_pre2/include:/opt/yunibase/current/gauche/lib/gauche-0.98/site/include")
    ("--archdirs"      "/opt/yunibase/current/gauche/lib/gauche-0.98/0.9.13_pre2/x86_64-pc-linux-gnu:/opt/yunibase/current/gauche/lib/gauche-0.98/site/x86_64-pc-linux-gnu")
    ("--local-incdir"  "")
    ("--local-libdir"  "")

    ("--default-cflags"  "-g -O2 -Wall -Wextra -Wno-unused-label")

    ("--object-suffix"   "o")
    ("--executable-suffix"  "")
    ("--rpath-flag"      "-Wl,--rpath=")
    ("--so-suffix"       "so")
    ("--so-cflags"       "-fPIC")
    ("--so-ldflags"      " -shared -o")
    ("--so-libs"         "")
    ("--dylib-suffix"    "so")
    ("--dylib-ldflags"   " -shared -o")
    ("--libgauche-so"    "libgauche-0.98.so")
    ("--static-libs"     "-lgauche-static-0.98     -lz    -lcrypt -lrt -lm  -lpthread")
    )))

