;; Bigloo release number
"4.5b"

;; Bigloo specific version
""

;; Bigloo configuration options
`((have-shared-library . ,(not (=fx 1 0)))
  (static-link-option . "")
  (shared-link-option . "")
  (c-strip-flag . "-s")
  (non-custom-gc-directory . "")
  (dlopen-lib . "-ldl")
  (have-dlopen . ,(not (=fx 1 0)))
  (release-number . "4.5b")
  (specific-version . "")
  (c-compiler-style . "gcc")
  (c-compiler . "gcc")
  (c-flags . "  -Wno-unused-value -Wno-parentheses-equality -Wno-parentheses -Wno-invalid-source-encoding -Wno-return-type -Wno-trigraphs")
  (c-pic-flag . "-fPIC")
  (c-nan-flag . "-DBGL_NAN_TAGGING=0")
  (c-compiler-o-option . "-o ")
  (c-compiler-debug-option . "-g")
  (c-compiler-optim-flag . "-O3")
  (c-prof-flag . "-pg -fno-inline   -Wno-unused-value -Wno-parentheses-equality -Wno-parentheses -Wno-invalid-source-encoding -Wno-return-type -Wno-trigraphs")
  (c-object-file-extension . "o")
  (c-string-split . ,(not (=fx 0 0)))
  (c-linker-style . "gcc")
  (c-linker-flags . " ")
  (c-linker-o-option . "-o ")
  (c-linker-debug-option . "-g ")
  (c-linker-optim-flags . "")
  (c-linker-soname-option . "-Wl,-soname")
  (c-ld . "gcc")
  (c-ld-option . "-shared")
  (library-directory . "/opt/yunibase/current/bigloo/lib/bigloo/4.5b")
  (dll-directory . "/opt/yunibase/current/bigloo/lib/bigloo/4.5b")
  (user-libraries . "-ldl -lresolv -lunistring -lpcre2-8 -lgmp -lm -lc")
  (default-back-end . "native")
  (gc-lib . "bigloogc")
  (gc-custom . ,(not (=fx 1 0)))
  (endianess . ,(if (=fx 0 0) 'little-endian 'big-endian))
  (homeurl . "http://www-sop.inria.fr/indes/fp/Bigloo")
  (shell . "/bin/sh")
  (ld-library-dir . "/opt/yunibase/current/bigloo/lib")
  (zip-directory . "/opt/yunibase/current/bigloo/lib/bigloo/4.5b")
  (c-beautifier . "")
  (dirname-cmd . "dirname")
  (library-base-name . "bigloo")
  (heap-debug-copt . "")
  (auto-finalizer . ,(not (=fx 0 0)))
  (have-bigloo-abort . ,(not (=fx 0 0)))
  (java . "java")
  (jar . "")
  (java-shell . "sh")
  (jflags . "")
  (jvflags . "")
  (have-bdb . ,(not (=fx 0 0)))
  (dns-cache-enabled . ,(not (=fx 1 0)))
  (shell-mv . "mv")
  (shell-rm . "rm")
  (regexp . "pcre2")
  (int-size . 61)
  (elong-size . 64)
  (os-class . "unix")
  (os-name . "linux")
  (os-arch . "x86_64")
  (os-version . "5.15.0-67-generic")
  (have-unistring . ,(=fx 1 1))
  (have-overflow . ,(=fx 1 1))
  (have-alloca . ,(=fx 1 1))
  (have-c99stackalloc . ,(=fx 1 1)))
  
