;; generated by unixstyle-install
#hash(
      (doc-dir . "/opt/yunibase/current/racket/share/doc/racket")
      (lib-dir . "/opt/yunibase/current/racket/lib/racket")
      (pkgs-dir . "/opt/yunibase/current/racket/share/racket/pkgs")
      (share-dir . "/opt/yunibase/current/racket/share/racket")
      (include-dir . "/opt/yunibase/current/racket/include/racket")
      (bin-dir . "/opt/yunibase/current/racket/bin")
      (apps-dir . "/opt/yunibase/current/racket/share/applications")
      (man-dir . "/opt/yunibase/current/racket/share/man")
      (absolute-installation? . #t)
      (compiled-file-roots . (same "/opt/yunibase/current/racket/lib/racket/compiled"))
)
